# if a message contains the keyword on the left, w i d e t o m will react with the emote on the right
# the emote name has to be the keyword
emotes = [
    ["conny", 838137360667508786],
    ["rene", 832636011917606912],
    ["yuki", 820785209527631892],
    ["nick", 816429590687776839],
    ["nils", 816429379654516796],
    ["tom", 811324632082415626],
    ["thomas", 803607136000802827],
]

# if a message is a trigger (equals, not contains) then respond with the answer
responses = [
    ["tom", "<:tom:811324632082415626>"],
    ["hui", "PRAISE hUI, THE ALMIGHTY OR PERISH AS FOOLS!!!"],
]

# xp application zitate for the xp command
xp = ["Bin n Freund von Brit", "I will learn", "sehr gute experience can approve",
    "Keine Ahnung Bro", "Das hab ich mich actually auch schon gefragt", "Yo le diría que desactivara el modulo Autonick y reescribiera el nombre sin la parte del nivel",
    "eject the bot", "i'm getting held gunpoint to fill out this formular and i have no clue why...", "what Bot", "sex", "dude wtf why are fucjk you", "dreckscode",
    "ich brauche immer #command-testing, sonst recht gut", "#faq you", "<leere>", "I would call myself a friend of Conny"]